name: conventer

on:
  schedule:
    - cron: '0 0 * * 0'  
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v2

      - name: Instalowanie Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  #

      - name: Instalowanie pip
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyyaml PyQt5

      - name: Tworzenie .exe - pliku
        run: |
          pyinstaller --onefile -n program conv.py  

      - name: Artefact
        uses: actions/upload-artifact@v2
        with:
          name: program.exe 
          path: dist/program.exe  
