name: conv

on:
  schedule:
    - cron: "0 0 * * 0" 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 
    
    - name: install
      run: |
        pip install pyinstaller
        pip install pyyaml
        pip install PyQt5
        
