name: conv

on:
  schedule:
    - cron: "0 0 * * 0" 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 
    
    - name: install
      run: |
        pip install pyinstaller
        pip install pyyaml
        pip install PyQt5
        
    - name: Tworzenie pliku .exe
      run: python setup.py build_exe # Замініть setup.py на шлях до вашого скрипта, що створює .exe-файл
    
    - name: Завантаження .exe-файлу в артефакти
      uses: actions/upload-artifact@v3
      with:
        name: my-app-exe
        path: dist/my-app.exe # Замініть dist/my-app.exe на шлях до вашого .exe-файлу в папці dist
